"""
Report Generator - Step 6 of GapFinder pipeline
Creates final Research Gap Report
"""

import json
from datetime import datetime

class ReportGenerator:
    def __init__(self, model):
        self.model = model
    
    def generate(self, topic, ranked_gaps, papers_data):
        """
        Generate final research gap report
        """
        # If no gaps found, create simple report
        if not ranked_gaps:
            return self._generate_simple_report(topic, papers_data)
        
        # Prepare data for LLM
        gaps_summary = []
        for i, gap in enumerate(ranked_gaps[:10]):  # Top 10 gaps
            gaps_summary.append({
                "rank": i + 1,
                "description": gap.get('description', ''),
                "gps_score": gap.get('gps_score', 0),
                "gap_type": gap.get('gap_type', 'general'),
                "supporting_papers_count": len(gap.get('supporting_papers', []))
            })
        
        prompt = f"""
Generate a professional Research Gap Report for:

TOPIC: {topic}
DATE: {datetime.now().strftime('%B %d, %Y')}
PAPERS ANALYZED: {len(papers_data)} papers

TOP GAPS IDENTIFIED:
{json.dumps(gaps_summary, indent=2)}

Create a report with these EXACT sections. Use markdown formatting:

# Research Gap Report: {topic}

## Executive Summary
[Write 2-3 paragraphs summarizing the current state of research and the main gaps found]

## Methodology
This report was generated using GapFinder, an LLM-based agent that:
- Retrieved {len(papers_data)} relevant papers from Semantic Scholar
- Analyzed each paper for methods, limitations, and future work
- Synthesized cross-paper patterns using Chain-of-Thought reasoning
- Ranked gaps using Gap Priority Score (GPS) = (Frequency/N) × Recency × Specificity

## Top Research Gaps (Ranked by Priority)

### Rank 1: [Gap description] (GPS = X.XX)
- **Gap Type**: [type]
- **Evidence**: This gap is mentioned/inferred from [number] papers
- **Why Important**: [Explain significance]
- **Recommended Action**: [Specific research direction to address this gap]

### Rank 2: [Next gap...]
[Repeat for top 5-7 gaps]

## Under-explored Methods
[List methods that appear in other domains but not yet applied here]

## Dataset Limitations
[Note any dataset gaps or underrepresented areas]

## Conclusion
[Summary and recommended first steps for researchers]

## References
[List key papers analyzed]

Return ONLY the markdown report, no other text or explanations.
"""
        
        try:
            response = self.model.generate_content(prompt)
            report = response.text
            return report
        except:
            return self._generate_simple_report(topic, papers_data, ranked_gaps)
    
    def _generate_simple_report(self, topic, papers_data, ranked_gaps=None):
        """Fallback report generation if LLM fails"""
        report = f"""# Research Gap Report: {topic}

**Generated by GapFinder**  
**Date:** {datetime.now().strftime('%B %d, %Y')}  
**Papers Analyzed:** {len(papers_data)}

---

## Executive Summary

This report identifies research gaps in the field of **{topic}** based on analysis of {len(papers_data)} academic papers. The analysis focuses on limitations stated in papers, suggested future work, and methodological patterns across the literature.

---

## Top Research Gaps

"""
        if ranked_gaps:
            for i, gap in enumerate(ranked_gaps[:5], 1):
                report += f"""
### Gap {i}: {gap.get('description', 'Research gap identified')}
- **GPS Score:** {gap.get('gps_score', 'N/A')}
- **Gap Type:** {gap.get('gap_type', 'general')}
- **Supporting Evidence:** {gap.get('frequency', 0)} papers mention this gap

"""
        else:
            report += """
### Gap 1: Limited application of advanced AI methods
Further research is needed to apply state-of-the-art AI techniques to this domain.

### Gap 2: Lack of standardized benchmarks
There is a need for standardized datasets and evaluation metrics.

### Gap 3: Limited real-world validation
Most existing work lacks validation in practical, real-world settings.

"""

        report += f"""
---

## Key Papers Analyzed

| # | Paper Title | Year |
|---|-------------|------|
"""
        for i, paper in enumerate(papers_data[:10], 1):
            title = paper.get('title', 'Unknown')[:60]
            year = paper.get('year', 'N/A')
            report += f"| {i} | {title} | {year} |\n"

        report += f"""

---

## Conclusion

Based on the analysis of {len(papers_data)} papers, several research opportunities exist in {topic}. Researchers should prioritize gaps with higher GPS scores as they represent areas with strong supporting evidence and high potential impact.

*Report generated automatically by GapFinder - LLM-based Research Gap Identification Agent*
"""
        return report